create extension if not exists pgcrypto;

create type public.question_status as enum ('waiting', 'answered');
create type public.question_category as enum ('프로그래밍', '웹개발', '디자인', '기타');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 1 and 20),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.questions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 10000),
  category public.question_category not null,
  status public.question_status not null default 'waiting',
  views bigint not null default 0 check (views >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 30)
);

create table public.question_tags (
  question_id uuid not null references public.questions(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (question_id, tag_id)
);

create index questions_created_at_idx on public.questions(created_at desc);
create index questions_views_idx on public.questions(views desc);
create index questions_category_idx on public.questions(category);
create index answers_question_id_idx on public.answers(question_id);
create index question_tags_tag_id_idx on public.question_tags(tag_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger questions_set_updated_at before update on public.questions
for each row execute function public.set_updated_at();

create trigger answers_set_updated_at before update on public.answers
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'), ''), split_part(new.email, '@', 1)), 20),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.sync_question_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_question_id uuid;
begin
  if tg_op = 'DELETE' then
    target_question_id := old.question_id;
  else
    target_question_id := new.question_id;
  end if;
  update public.questions
  set status = case
    when exists (select 1 from public.answers where question_id = target_question_id) then 'answered'::public.question_status
    else 'waiting'::public.question_status
  end
  where id = target_question_id;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger answers_sync_question_status after insert or delete on public.answers
for each row execute function public.sync_question_status();

create or replace function public.increment_question_views(question_id uuid)
returns bigint
language sql
security definer
set search_path = ''
as $$
  update public.questions
  set views = views + 1
  where id = question_id
  returning views;
$$;

create or replace function public.create_question_with_tags(
  question_title text,
  question_content text,
  question_category text,
  tag_names text[]
)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  new_question_id uuid;
  tag_name text;
  new_tag_id bigint;
begin
  insert into public.questions (user_id, title, content, category)
  values (auth.uid(), question_title, question_content, question_category::public.question_category)
  returning id into new_question_id;

  foreach tag_name in array tag_names loop
    insert into public.tags (name) values (tag_name)
    on conflict (name) do nothing;
    select id into new_tag_id from public.tags where name = tag_name;
    insert into public.question_tags (question_id, tag_id) values (new_question_id, new_tag_id);
  end loop;
  return new_question_id;
end;
$$;

create or replace function public.update_question_with_tags(
  question_id uuid,
  question_title text,
  question_content text,
  question_category text,
  tag_names text[]
)
returns void
language plpgsql
set search_path = ''
as $$
declare
  tag_name text;
  new_tag_id bigint;
begin
  update public.questions
  set title = question_title, content = question_content, category = question_category::public.question_category
  where id = question_id and user_id = auth.uid();
  if not found then raise exception '질문을 수정할 권한이 없습니다.'; end if;

  delete from public.question_tags where question_tags.question_id = update_question_with_tags.question_id;
  foreach tag_name in array tag_names loop
    insert into public.tags (name) values (tag_name)
    on conflict (name) do nothing;
    select id into new_tag_id from public.tags where name = tag_name;
    insert into public.question_tags (question_id, tag_id) values (update_question_with_tags.question_id, new_tag_id);
  end loop;
end;
$$;

create view public.question_feed
with (security_invoker = true)
as
select
  q.id,
  q.user_id,
  q.title,
  q.content,
  q.category,
  q.status,
  q.views,
  q.created_at,
  q.updated_at,
  p.username,
  p.avatar_url,
  count(distinct a.id)::int as answer_count,
  coalesce(jsonb_agg(distinct t.name) filter (where t.name is not null), '[]'::jsonb) as tags
from public.questions q
join public.profiles p on p.id = q.user_id
left join public.answers a on a.question_id = q.id
left join public.question_tags qt on qt.question_id = q.id
left join public.tags t on t.id = qt.tag_id
group by q.id, p.id;

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.tags enable row level security;
alter table public.question_tags enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "questions are public" on public.questions for select using (true);
create policy "authenticated users create questions" on public.questions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "authors update questions" on public.questions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "authors delete questions" on public.questions for delete to authenticated using ((select auth.uid()) = user_id);

create policy "answers are public" on public.answers for select using (true);
create policy "authenticated users create answers" on public.answers for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "authors update answers" on public.answers for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "authors delete answers" on public.answers for delete to authenticated using ((select auth.uid()) = user_id);

create policy "tags are public" on public.tags for select using (true);
create policy "authenticated users create tags" on public.tags for insert to authenticated with check (true);
create policy "question tags are public" on public.question_tags for select using (true);
create policy "authors add question tags" on public.question_tags for insert to authenticated with check (exists (select 1 from public.questions q where q.id = question_id and q.user_id = (select auth.uid())));
create policy "authors delete question tags" on public.question_tags for delete to authenticated using (exists (select 1 from public.questions q where q.id = question_id and q.user_id = (select auth.uid())));

revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.sync_question_status() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.increment_question_views(uuid) from public;
grant execute on function public.increment_question_views(uuid) to anon, authenticated;
revoke all on function public.create_question_with_tags(text, text, text, text[]) from public, anon;
grant execute on function public.create_question_with_tags(text, text, text, text[]) to authenticated;
revoke all on function public.update_question_with_tags(uuid, text, text, text, text[]) from public, anon;
grant execute on function public.update_question_with_tags(uuid, text, text, text, text[]) to authenticated;
